image: python:3.8-buster

tasks:
  - command: unset PIP_USER && pip install virtualenv && virtualenv .venv && source .venv/bin/activate && pip install -r requirements.txt && FLASK_APP=main.py FLASK_ENV=development flask run --port 8000

ports:
  - port: 8000
